
export class LessonApp {
  constructor(root, lesson){this.root=root;this.lesson=lesson;this.index=0;this.screens=[];}
  mount(){document.title=this.lesson.title;document.querySelector('.brand').textContent=this.lesson.title;this.root.innerHTML=this.lesson.sections.map((s,i)=>this.renderSection(s,i)).join('');this.screens=[...this.root.querySelectorAll('.screen')];this.bind();this.show(0);document.dispatchEvent(new CustomEvent('lesson-mounted',{detail:this.lesson}));}
  renderSection(s,i){const type=s.type||'content';if(type==='intro')return `<section class="screen"><span class="eyebrow">Введение</span><h1>${s.title}</h1><p class="lead">${s.lead}</p><div class="card observe"><h3>Зачем изучать эту тему</h3><p>${s.purpose}</p></div><div class="card idea"><h3>Что уже нужно знать</h3><p>${s.prereq}</p></div></section>`;
    if(type==='steps')return `<section class="screen"><span class="eyebrow">${s.label||'Путь к правилу'}</span><h2>${s.title}</h2><div class="steps">${s.items.map((x,j)=>`<div class="step"><span class="num">${j+1}</span><div>${x}</div></div>`).join('')}</div>${s.note?`<div class="note">${s.note}</div>`:''}</section>`;
    if(type==='demo')return `<section class="screen"><span class="eyebrow">Исследование</span><h2>${s.title}</h2><p>${s.text||''}</p><div class="demo" data-demo="${s.demo}"></div></section>`;
    if(type==='tasks')return `<section class="screen"><span class="eyebrow">Практика</span><h2>${s.title}</h2><div data-static-tasks></div></section>`;
    if(type==='factory')return `<section class="screen"><span class="eyebrow">Генератор задач</span><h2>${s.title}</h2><div class="task factory" data-factory></div></section>`;
    if(type==='summary')return `<section class="screen"><span class="eyebrow">Итог</span><h2>${s.title}</h2><div class="card idea"><ol>${s.items.map(x=>`<li>${x}</li>`).join('')}</ol></div></section>`;
    return `<section class="screen"><span class="eyebrow">${s.label||'Объяснение'}</span><h2>${s.title}</h2>${s.html}</section>`;}
  bind(){document.getElementById('prev').onclick=()=>this.show(this.index-1);document.getElementById('next').onclick=()=>this.show(this.index+1);document.getElementById('menu').onclick=()=>this.openToc();}
  show(n){this.index=Math.max(0,Math.min(n,this.screens.length-1));this.screens.forEach((x,i)=>x.classList.toggle('active',i===this.index));document.querySelector('.progress i').style.width=((this.index+1)/this.screens.length*100)+'%';document.getElementById('count').textContent=`${this.index+1} / ${this.screens.length}`;document.getElementById('prev').disabled=this.index===0;document.getElementById('next').textContent=this.index===this.screens.length-1?'Готово ✓':'Далее →';scrollTo({top:0,behavior:'smooth'});}
  openToc(){const names=this.lesson.sections.map((x,i)=>x.title||`Раздел ${i+1}`);this.root.insertAdjacentHTML('beforeend',`<section class="screen" id="tocScreen"><span class="eyebrow">Оглавление</span><h2>Разделы урока</h2><div class="toc">${names.map((x,i)=>`<button data-go="${i}">${i+1}. ${x}</button>`).join('')}</div></section>`);this.screens=[...this.root.querySelectorAll('.screen')];const t=this.screens.length-1;t;this.root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{document.getElementById('tocScreen').remove();this.screens=[...this.root.querySelectorAll('.screen')];this.show(+b.dataset.go)});this.show(t);}
}
